/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RandomRouteImport } from './routes/random'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated/workflows'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTaskHistoryRouteImport } from './routes/_authenticated/task-history'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedOrganizationGraphRouteImport } from './routes/_authenticated/organization-graph'
import { Route as AuthenticatedMemoryRouteImport } from './routes/_authenticated/memory'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAiTasksRouteImport } from './routes/_authenticated/ai-tasks'
import { Route as AuthenticatedAiDepartmentsRouteImport } from './routes/_authenticated/ai-departments'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedDocumentsDocumentIdRouteImport } from './routes/_authenticated/documents.$documentId'
import { Route as AuthenticatedAiTasksTaskIdRouteImport } from './routes/_authenticated/ai-tasks.$taskId'
import { Route as AuthenticatedAiDepartmentsSlugRouteImport } from './routes/_authenticated/ai-departments.$slug'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomRoute = RandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaskHistoryRoute =
  AuthenticatedTaskHistoryRouteImport.update({
    id: '/task-history',
    path: '/task-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationGraphRoute =
  AuthenticatedOrganizationGraphRouteImport.update({
    id: '/organization-graph',
    path: '/organization-graph',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMemoryRoute = AuthenticatedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiTasksRoute = AuthenticatedAiTasksRouteImport.update({
  id: '/ai-tasks',
  path: '/ai-tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiDepartmentsRoute =
  AuthenticatedAiDepartmentsRouteImport.update({
    id: '/ai-departments',
    path: '/ai-departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsDocumentIdRoute =
  AuthenticatedDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiTasksTaskIdRoute =
  AuthenticatedAiTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => AuthenticatedAiTasksRoute,
  } as any)
const AuthenticatedAiDepartmentsSlugRoute =
  AuthenticatedAiDepartmentsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedAiDepartmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/random': typeof RandomRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/ai-departments': typeof AuthenticatedAiDepartmentsRouteWithChildren
  '/ai-tasks': typeof AuthenticatedAiTasksRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/health': typeof AuthenticatedHealthRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/organization-graph': typeof AuthenticatedOrganizationGraphRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/task-history': typeof AuthenticatedTaskHistoryRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/ai-departments/$slug': typeof AuthenticatedAiDepartmentsSlugRoute
  '/ai-tasks/$taskId': typeof AuthenticatedAiTasksTaskIdRoute
  '/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/random': typeof RandomRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/ai-departments': typeof AuthenticatedAiDepartmentsRouteWithChildren
  '/ai-tasks': typeof AuthenticatedAiTasksRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/health': typeof AuthenticatedHealthRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/organization-graph': typeof AuthenticatedOrganizationGraphRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/task-history': typeof AuthenticatedTaskHistoryRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/ai-departments/$slug': typeof AuthenticatedAiDepartmentsSlugRoute
  '/ai-tasks/$taskId': typeof AuthenticatedAiTasksTaskIdRoute
  '/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/random': typeof RandomRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/ai-departments': typeof AuthenticatedAiDepartmentsRouteWithChildren
  '/_authenticated/ai-tasks': typeof AuthenticatedAiTasksRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/memory': typeof AuthenticatedMemoryRoute
  '/_authenticated/organization-graph': typeof AuthenticatedOrganizationGraphRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/task-history': typeof AuthenticatedTaskHistoryRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRoute
  '/_authenticated/ai-departments/$slug': typeof AuthenticatedAiDepartmentsSlugRoute
  '/_authenticated/ai-tasks/$taskId': typeof AuthenticatedAiTasksTaskIdRoute
  '/_authenticated/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/help'
    | '/onboarding'
    | '/random'
    | '/reset-password'
    | '/activity'
    | '/ai-departments'
    | '/ai-tasks'
    | '/dashboard'
    | '/departments'
    | '/health'
    | '/knowledge'
    | '/memory'
    | '/organization-graph'
    | '/overview'
    | '/profile'
    | '/settings'
    | '/task-history'
    | '/tasks'
    | '/templates'
    | '/workflows'
    | '/ai-departments/$slug'
    | '/ai-tasks/$taskId'
    | '/documents/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/help'
    | '/onboarding'
    | '/random'
    | '/reset-password'
    | '/activity'
    | '/ai-departments'
    | '/ai-tasks'
    | '/dashboard'
    | '/departments'
    | '/health'
    | '/knowledge'
    | '/memory'
    | '/organization-graph'
    | '/overview'
    | '/profile'
    | '/settings'
    | '/task-history'
    | '/tasks'
    | '/templates'
    | '/workflows'
    | '/ai-departments/$slug'
    | '/ai-tasks/$taskId'
    | '/documents/$documentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/help'
    | '/onboarding'
    | '/random'
    | '/reset-password'
    | '/_authenticated/activity'
    | '/_authenticated/ai-departments'
    | '/_authenticated/ai-tasks'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/health'
    | '/_authenticated/knowledge'
    | '/_authenticated/memory'
    | '/_authenticated/organization-graph'
    | '/_authenticated/overview'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/task-history'
    | '/_authenticated/tasks'
    | '/_authenticated/templates'
    | '/_authenticated/workflows'
    | '/_authenticated/ai-departments/$slug'
    | '/_authenticated/ai-tasks/$taskId'
    | '/_authenticated/documents/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HelpRoute: typeof HelpRoute
  OnboardingRoute: typeof OnboardingRoute
  RandomRoute: typeof RandomRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random': {
      id: '/random'
      path: '/random'
      fullPath: '/random'
      preLoaderRoute: typeof RandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/task-history': {
      id: '/_authenticated/task-history'
      path: '/task-history'
      fullPath: '/task-history'
      preLoaderRoute: typeof AuthenticatedTaskHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organization-graph': {
      id: '/_authenticated/organization-graph'
      path: '/organization-graph'
      fullPath: '/organization-graph'
      preLoaderRoute: typeof AuthenticatedOrganizationGraphRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memory': {
      id: '/_authenticated/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthenticatedMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-tasks': {
      id: '/_authenticated/ai-tasks'
      path: '/ai-tasks'
      fullPath: '/ai-tasks'
      preLoaderRoute: typeof AuthenticatedAiTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-departments': {
      id: '/_authenticated/ai-departments'
      path: '/ai-departments'
      fullPath: '/ai-departments'
      preLoaderRoute: typeof AuthenticatedAiDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$documentId': {
      id: '/_authenticated/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-tasks/$taskId': {
      id: '/_authenticated/ai-tasks/$taskId'
      path: '/$taskId'
      fullPath: '/ai-tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedAiTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedAiTasksRoute
    }
    '/_authenticated/ai-departments/$slug': {
      id: '/_authenticated/ai-departments/$slug'
      path: '/$slug'
      fullPath: '/ai-departments/$slug'
      preLoaderRoute: typeof AuthenticatedAiDepartmentsSlugRouteImport
      parentRoute: typeof AuthenticatedAiDepartmentsRoute
    }
  }
}

interface AuthenticatedAiDepartmentsRouteChildren {
  AuthenticatedAiDepartmentsSlugRoute: typeof AuthenticatedAiDepartmentsSlugRoute
}

const AuthenticatedAiDepartmentsRouteChildren: AuthenticatedAiDepartmentsRouteChildren =
  {
    AuthenticatedAiDepartmentsSlugRoute: AuthenticatedAiDepartmentsSlugRoute,
  }

const AuthenticatedAiDepartmentsRouteWithChildren =
  AuthenticatedAiDepartmentsRoute._addFileChildren(
    AuthenticatedAiDepartmentsRouteChildren,
  )

interface AuthenticatedAiTasksRouteChildren {
  AuthenticatedAiTasksTaskIdRoute: typeof AuthenticatedAiTasksTaskIdRoute
}

const AuthenticatedAiTasksRouteChildren: AuthenticatedAiTasksRouteChildren = {
  AuthenticatedAiTasksTaskIdRoute: AuthenticatedAiTasksTaskIdRoute,
}

const AuthenticatedAiTasksRouteWithChildren =
  AuthenticatedAiTasksRoute._addFileChildren(AuthenticatedAiTasksRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAiDepartmentsRoute: typeof AuthenticatedAiDepartmentsRouteWithChildren
  AuthenticatedAiTasksRoute: typeof AuthenticatedAiTasksRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedMemoryRoute: typeof AuthenticatedMemoryRoute
  AuthenticatedOrganizationGraphRoute: typeof AuthenticatedOrganizationGraphRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTaskHistoryRoute: typeof AuthenticatedTaskHistoryRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRoute
  AuthenticatedDocumentsDocumentIdRoute: typeof AuthenticatedDocumentsDocumentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAiDepartmentsRoute: AuthenticatedAiDepartmentsRouteWithChildren,
  AuthenticatedAiTasksRoute: AuthenticatedAiTasksRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedMemoryRoute: AuthenticatedMemoryRoute,
  AuthenticatedOrganizationGraphRoute: AuthenticatedOrganizationGraphRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTaskHistoryRoute: AuthenticatedTaskHistoryRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRoute,
  AuthenticatedDocumentsDocumentIdRoute: AuthenticatedDocumentsDocumentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HelpRoute: HelpRoute,
  OnboardingRoute: OnboardingRoute,
  RandomRoute: RandomRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
